name = "floorplan-editor"
main = "src/index.ts"
compatibility_date = "2025-10-23"

[images]
binding = "IMAGES"

[vars]
ACCOUNT_ID = "xxxxx"
IMAGES_ACCOUNT_BASE = "https://api.cloudflare.com/client/v4/accounts/xxxxx/images/v1"
